Votaciones/Models/Persona.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Votaciones.Models
{
    public class Persona
    {
        [Key]
        public int idPersona { get; set; }

        [Display(Name = "Nombre")]
        [Required(ErrorMessage = "Usted debe ingresar {0}")]
        [StringLength(50, ErrorMessage = "El campo {0} debe tener minimo {2} caracteres.", MinimumLength = 3)]
        public string nombrePersona { get; set; }

        [Display(Name = "Usuario")]
        [Required(ErrorMessage = "Usted debe ingresar {0}")]
        [StringLength(50, ErrorMessage = "El campo {0} debe tener minimo {2} caracteres.", MinimumLength = 3)]
        [Index("usuarioIndex", IsUnique = true)]
        public string usuario { get; set; }

        [Display(Name = "Correo electrónico")]
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "Usted debe ingresar {0}")]
        public string email { get; set; }

        [Display(Name = "Cargo")]
      
        public string cargo { get; set; }

        public string grupo { get; set; }

        [Display(Name = "Foto")]
        [DataType(DataType.ImageUrl)]
        public string foto { get; set; }
        public virtual ICollection<MiembroDeGrupo> miembrosDeGrupo { get; set; }

    }
}

Votaciones/Controllers/PersonasController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Votaciones.Models;

namespace Votaciones.Controllers
{
    [Authorize]
    public class PersonasController : Controller
    {
        private VotacionesContext db = new VotacionesContext();

        // GET: Personas
        public ActionResult Index()
        {
            return View(db.Personas.ToList());
        }

        // GET: Personas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Persona persona = db.Personas.Find(id);
            if (persona == null)
            {
                return HttpNotFound();
            }
            return View(persona);
        }

        // GET: Personas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Personas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( PersonaVista personaVista)
        {
            if (!ModelState.IsValid)
            {
                return View(personaVista);
            }
            string path = string.Empty;
            string pic = string.Empty;
            if(personaVista.foto!=null)
            {
                pic = Path.GetFileName(personaVista.foto.FileName);
                path = Path.Combine(Server.MapPath("~/Content/Fotos"), pic);
                personaVista.foto.SaveAs(path);
                using (MemoryStream ms = new MemoryStream())
                {
                    personaVista.foto.InputStream.CopyTo(ms);
                    byte[] array = ms.GetBuffer();
                }
            }
            var persona = new Persona
            {
                nombrePersona = personaVista.nombrePersona,
                usuario=personaVista.usuario,
                email=personaVista.email,
                cargo= personaVista.cargo,
                grupo=personaVista.grupo,
                foto=pic==string.Empty ? string.Empty : string.Format("~/Content/Fotos/{0}",pic)
            };

            db.Personas.Add(persona);

            try
            {
                db.SaveChanges();
                this.CreateASPUser(personaVista);                                                                                                                                                                                       
            }
            catch (Exception ex)
            {
                if (ex.InnerException != null &&ex.InnerException.InnerException!=null&&ex.InnerException.InnerException.Message.Contains("usuarioIndex"))
                {
                    ViewBag.Error = " El nombre usuario es usado por otro usuario ";
                }
                else
                {
                    ViewBag.Error = ex.Message;
                }
                return View(personaVista);
            }

            return RedirectToAction("Index");

                    }

        private void CreateASPUser(PersonaVista personaVista)
        {
            var userContext = new ApplicationDbContext();
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(userContext));
            var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(userContext));

            string roleName = "User";

            if (!roleManager.RoleExists(roleName))
            {
                roleManager.Create(new IdentityRole(roleName));
            }

            var userASP = new ApplicationUser
            {
                UserName=personaVista.usuario,
                Email=personaVista.email
     
            };
            userManager.Create(userASP, userASP.UserName);

            userASP = userManager.FindByName(personaVista.usuario);
            userManager.AddToRole(userASP.Id, "Usuario");
        }

        // GET: Personas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Persona persona = db.Personas.Find(id);
            if (persona == null)
            {
                return HttpNotFound();
            }
            var personaVista= new PersonaVista
            {
                nombrePersona = persona.nombrePersona,
                usuario = persona.usuario,
                email= persona.email,
                cargo = persona.cargo,
                idPersona=persona.idPersona,
                grupo=persona.grupo
                
            };
            return View(personaVista);
        }

        // POST: Personas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PersonaVista personaVista)
        {
            if (!ModelState.IsValid)
            {
                return View(personaVista);
            }
            string path = string.Empty;
            string pic = string.Empty;
            if (personaVista.foto != null)
            {
                pic = Path.GetFileName(personaVista.foto.FileName);
                path = Path.Combine(Server.MapPath("~/Content/Fotos"), pic);
                personaVista.foto.SaveAs(path);
                using (MemoryStream ms = new MemoryStream())
                {
                    personaVista.foto.InputStream.CopyTo(ms);
                    byte[] array = ms.GetBuffer();
                }
            }
            var persona = db.Personas.Find(personaVista.idPersona);

            persona.nombrePersona = personaVista.nombrePersona;
            persona.usuario = personaVista.usuario;
            persona.cargo = personaVista.cargo;
            persona.grupo = personaVista.grupo;
            persona.email = personaVista.email;
            if(!string.IsNullOrEmpty(pic))
            {
                persona.foto = pic == string.Empty ? string.Empty : string.Format("~/Content/Fotos/{0}", pic);
            }
           
            
            db.Entry(persona).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
            
        }

        // GET: Personas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Persona persona = db.Personas.Find(id);
            if (persona == null)
            {
                return HttpNotFound();
            }
            return View(persona);
        }

        // POST: Personas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Persona persona = db.Personas.Find(id);
            db.Personas.Remove(persona);
            db.SaveChanges();
            try
            {
                db.SaveChanges();
            }
            catch (Exception ex)
            {
                if (ex.InnerException != null &&
                    ex.InnerException.InnerException != null &&
                    ex.InnerException.InnerException.Message.Contains("REFERENCE"))
                {
                    ViewBag.Error = "No se puede borrar el elemento porque está relacionado con otros datos";
                }
                else
                {
                    ViewBag.Error = ex.Message;
                }
                return View(persona);
            }
                return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Votaciones/Views/Personas/Create.cshtml
@model Votaciones.Models.PersonaVista

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
<h3>@ViewBag.Error</h3>

@using (Html.BeginForm("Create", "Personas", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Persona</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nombrePersona, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombrePersona, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombrePersona, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.usuario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.usuario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.usuario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cargo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cargo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cargo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.grupo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.grupo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.grupo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.foto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span class="btn btn-default btn-file">
                    @Html.TextBoxFor(modelo => modelo.foto, new { type = "file" })
                </span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Votaciones/Views/Personas/Delete.cshtml
@model Votaciones.Models.Persona

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>
<h3>@ViewBag.Error</h3>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Persona</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombrePersona)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombrePersona)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.usuario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.usuario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cargo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cargo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.grupo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.grupo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.foto)
        </dt>

        <dd>
            @if (!string.IsNullOrEmpty(Model.foto))
            {
                <img src="@Url.Content(Model.foto)" alt="Image" style="width:200px;height:200px;max-width:100%;height:auto;" />
            }
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Votaciones/Views/Personas/Details.cshtml
@model Votaciones.Models.Persona

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Persona</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombrePersona)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombrePersona)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.usuario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.usuario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cargo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cargo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.grupo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.grupo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.foto)
        </dt>

        <dd>
            @if (!string.IsNullOrEmpty(Model.foto))
            {
                <img src="@Url.Content(Model.foto)" alt="Image" style="width:100px;height:100px;max-width:100%;height:auto;" />
            }
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.idPersona }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Votaciones/Views/Personas/Edit.cshtml
@model Votaciones.Models.PersonaVista

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Personas", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Persona</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idPersona)
        @Html.HiddenFor(model => model.nombrePersona)
        @Html.HiddenFor(model => model.usuario)
        @Html.HiddenFor(model => model.foto)
        @Html.HiddenFor(model => model.cargo)

        <div class="form-group">
            @Html.LabelFor(model => model.nombrePersona, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombrePersona, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombrePersona, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.usuario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.usuario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.usuario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cargo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cargo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cargo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.grupo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.grupo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.grupo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.foto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span class="btn btn-default btn-file">
                    @Html.TextBoxFor(modelo => modelo.foto, new { type = "file" })
                </span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Votaciones/Views/Personas/Index.cshtml
@model IEnumerable<Votaciones.Models.Persona>

@{
    ViewBag.Title = "Index";
}

<h2>Personas</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nombrePersona)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.usuario)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.cargo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.grupo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.foto)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.nombrePersona)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.usuario)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.cargo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.grupo)
        </td>
        <td>   
            @if(!string.IsNullOrEmpty(item.foto))
            {
                <img src="@Url.Content(item.foto)" alt="foto" style="width:100px;height:100px;max-width: 100%;height: auto;"/>
            }
             
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.idPersona }) |
            @Html.ActionLink("Details", "Details", new { id=item.idPersona }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.idPersona })
        </td>
    </tr>
}

</table>